# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MovieRama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieRama
  pod 'SwiftLint', '0.43.1'

  target 'MovieRamaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieRamaUITests' do
    # Pods for testing
  end

end
